name: Build and Deploy Images
inputs:
  docker-push-tag:
    required: true
  docker-host:
    required: true
  docker-username:
    required: true
  docker-password:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        registry: ${{docker-host}}
    - uses: ./.github/workflows/actions/cached-dependencies
    - uses: ./.github/workflows/actions/load-conf-env
    - name: Build Docker Images
      run: |
        set -eo pipefail
        source "$HOME/.nvm/nvm.sh"
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        source $GITHUB_WORKSPACE/devops/linux/docker/conf.env
        source $GITHUB_WORKSPACE/devops/linux/docker/conf/images/conf-app-images.sh 
        pushd $GITHUB_WORKSPACE/JeMPI_Apps
          source ./build-all-ci.sh "${{ inputs.docker-push-tag }}"
        popd
      shell: bash
