{
 "title": "JeMPI Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "DGraph Inuse Bytes",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "dgraph_memory_inuse_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total and Free Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalphysicalmemorysize",
     "legendFormat": "__auto"
    },
    {
     "expr": "java_lang_operatingsystem_freephysicalmemorysize",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "jvm_classes_currently_loaded", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "GC Pause Collection Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "java_lang_zgc_pauses_collectiontime",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZGC Collection Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "java_lang_zgc_cycles_collectiontime",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory before GC",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "java_lang_zgc_cycles_lastgcinfo_memoryusagebeforegc_init",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory after GC",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "java_lang_zgc_cycles_lastgcinfo_memoryusageaftergc_init",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "java_lang_threading_threadcount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true
  },
  {
   "title": "OS CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_cpuload",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_processcpuload",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}