FROM $JAVA_BASE_IMAGE

ADD $JAR_FILE /app/$JAR_FILE

RUN printf "#!/bin/bash\n\
    cd /app\n\
    java -server --enable-preview -XX:MaxRAMPercentage=80 -XX:+UseZGC -javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.17.2.jar=50010:/opt/prometheus/linker_prometheus.yml -jar /app/$JAR_FILE\n" > /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"] 
