FROM $JAVA_BASE_IMAGE

ADD $JAR_FILE /app/$JAR_FILE

RUN printf "#!/bin/bash\n\
    cd /app\n\
    java -server -Dcom.sun.management.jmxremote.port=3000 --enable-preview -XX:MaxRAMPercentage=80 -XX:+UseZGC -jar /app/$JAR_FILE\n" > /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"] 
